const char* const opening[] = {
	"GGGGGGGGGGGGGGeeeG  yXDDDzEee9                                                                      \n"
	"GGGGGGGGGGGGeeeG uyDDDDD9eee                                                                        \n"
	"GGGGGGGGGGeee5 ,5Dz9eeeeee                                                                          \n"
	"GGGGGGGGGeeeKu5DDzeeeX                                                                              \n"
	"GGGGGGGGGee WXDDz#e                                                                                 \n"
	"GGGGGGGeeeeWDD#eeee                                                                                 \n"
	"GGGGGGGe,K WzEee                                                                                    \n"
	"GGGGGGGGeeWX#99                              K                                                      \n"
	"GGGGGeeeeWW9ee                               e                                                      \n"
	"eeeeeeeEDKX#                                 5                                                      \n"
	"W  y   ,WXDEee                               K                                                      \n"
	"eeeeeezXzzz#eeW                                                                                     \n"
	"eeeeeeeeeeeeee                              eeeee                                                   \n"
	"                                            eeeee                                                   \n"
	"                                            e5Kze                                                   \n"
	"                                            e##ee#                                                  \n"
	"                                           9eWX9ee            W5y                                   \n"
	"                                   e9D#,W# eeuEyee          eeeKu                                   \n"
	"               5z u                e yzu e e5K,eee       e  ee           eee                        \n"
	"               ee                  e ,5,KG eeeeeee      ee  eeeee        eee     eee                \n"
	"               ee                  e,Ku   9eeeeeee      ee  eeEe        9eee     e,e                \n"
	"         K9eE  e#      e           e W5   eeeeeeee      ee  eeee y      eeee     e e                \n"
	" #     , eeee  eG     e u          e, uu, eeWX 5Xe  e   e,   eee XzW    e#ee   D e              eee \n"
	" ee eyeeeeeee  e      eeXu      ee,       eeG  9ee eeee eK e eee G  e, e   X     e     X        ,ee \n"
	",   e e   Xee  9XGee  e,         W5 eee   ee Ee eee # e e, e eeG  #eEe  Ee, ,ee  e   ee eeeee   #ee \n"
	"e   eee    ee eeeez9ee e  eeee Xee #eeee  ee  e# ee 5 e,eu e eee  eeee  De  e    e   ee yee e    ee \n"
	"eee ee  e e e,eee99eee e  eee eeee  e eee eeuze  eeee9eee  eeee9    ee  ee  ee#eeeee ee  ee eeeKWeyK\n"
	" ee eXGee e eeyeeeeeee e  eze eu ee#    y ee  e  eeeeeeee  eWeeeeeeeee  eeee   eeee  ee  ee ee  eeye\n"
	"eeEue eeeeeeeXyeeEeeee e  eeeeeeeeeeeeeWy ee99ey e ez   eeueEeeeeeeeXe  eeGe , eXGeeeee  eeeee  eeue\n"
	"eeeee,eeeee eeWeeeeeeeeeeue 9XezyD,ueEeeeeee9eeGeeeeeeeeeeeee9eeueee ee ,eGe  eeXee#eee5XeeeeeeeeW e\n"
	"eeeeezeeeeeEeE#eeeeee9e eEeeeeeeezeGeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee9ee eeeeEeeeeeeeeeeee ye eeeeeee\n"
	"z eeuKeeeeeeeeeeeeeeeeeeeeeez5eeeeeeeee5e   yKzeyeeeK D   WEezeeeeeeeeeeeeeeeeeEeEeeeee9ez9e#e#zy#GK\n"
	"Ge9eeeDeeGEeEee##eeeee#eXKGDeEee#EeeeeGeeeeeeeeeeeW9eeeeeee##EeXE#eee#ee9eE5Ge#eEueeeEeeG9ee ezeeeee\n"
	"eeeGeee5z9eeeeeeeG#EE9eXeeDeeeX,eEeX EEe 9eeeeeeEeee eeE#5DDWeee#u#e,#K# e ee9Kueuu ze W 9E eee9euz9\n"
	"uWX5e5Keee5zeeeeeeeE#Wee9eeeeeeeezeeeeeXKeEX5  9eeeeEzeeeeee eX,eeEeeeG 5eeyX eG, #e9EzeeeeX   y ee \n"
	"yeeeD  W  #    u   XeG5eeeD# X  KED ue9ee W #GeDe 9DeeXXyeEXee eW5  W 5EeeezeeeeeeeeEee    XeeeeEeee\n"
	"Deueeeeeeeeee z,eD         Ey,We  G K    eeeze #eee      De9eD XeWeezee                            \n"
	"eEz9eeyyez9#yeeeeeeeeeeeeeeeeeee5eeeeeeeeey Wyueu  ,eeze     KE   ezK9W   ※ 도시 풍경 사진 입니다\n"
	"XeXyyX,9,E##X     WeezyDzXEWu5WK#D9 9  u5DWeeGeeeeee,eeeeeeeDeeeeeee9 e                         \n"
	,
	"e  ee          e        ue#  WW  yeee uD                    z  uzeeeEeeezeD                      \n"
	"eee5           z           e# e  ee#eee              yeeeeee z  ee eeEeeeeD  ※ 좀비 사진 입니다\n"
	"Ee   Ge        ,               9eee                eeeeeeeeee eeyEe5e eeeeD                      \n"
	"Xe    eeeez E,                 e                 eeee    eeee   ,  9XeGeeeEDGeeeeeeeeeeeeeeeeeeeeeee\n"
	"z5#eeD  eWe   5     ,          DX e           WeeeX      eeeeeeX,G  9G yeee59GEeeeeeeeeeeeeeeeeeeeee\n"
	"e    W  e eee  X                            Weeee        eeeeeeee  u Ke  GezzGeeeeeeeeeeeeeeeeeeeeee\n"
	"eKuu , e   KeG5e    5         eee K   ,    u,Kee,       eeeKWeee      e  eeeXyEGeeeeeeeeeeeeeeeeeeee\n"
	"e  W e      e       ue        eeeW    K      eee,    eeee#eWeeeee         eeeGDEGeeeeeeeeeeeeeeeeeee\n"
	"e    X   e  u        e        G    De       eeeeeeeeeeGzee  5         Dee eueeEzeeeeeeeeeeeeeeeeeeee\n"
	"eXyE  z ue  5    , uX#G      u9     e    DXeeeGeeee,  eee ,zeXe           eeDee5#GGeeeeeeeeeeeeeeeee\n"
	"ee   W   eeee          K   W        e W u   eeeeeeeeeeeeeee eeee    e   e ezXeee5#eeeeeeeeeeeeeeeeee\n"
	"eeeDK  , eee      , K  X             e     eee#EGeeeeeee#   e  ,e   ee    eee#eee59GGeeeeeeeeeeeeeee\n"
	"Eeeeee#K eee   ,  u,Ku   5Xz                9eeeeezy          We   e    eee  eeeeeXEeeeeeeeeeeeeeeee\n"
	"e9GEeueeeeee9y             u     u#eeE #      eeKeee             e      z  ee eGee9DEGeeeeeeeeeeeeee\n"
	"eeE#eeeeXeeeeK     X           eeeeeeeeeG      uyKKWe        ueeeeeG9e#  e zeeeee eDD9Eeeeeeeeeeeeee\n"
	"eeG9zEezzDeeez     K       5eeeeeeee95eeee       5eeeeeeE   E,e      WGy  eK  5eeXeeX9#EGeeeeeeeeeee\n"
	"eeeeGzzee  eee9E   eeeee  eeee     eeW e  eD       eeeeeeee eeeeee,e#K9W    u  eeeKeeG59EEGeeeeeeeee\n"
	"eeeeGE#XGeeeee         eeeee      eeeeee eeu         eeeeee  D5eeGz  eE     W   eeee5eeWzEEGEeeeeeee\n"
	"eeeeeeEGDWeeXe#      eeKee        eeeeeE    #e           Xee X ,EuXu          e #eeeeXeeKX9E9EEGGeee\n"
	"eeeeeeeG#EGeeeeee     eeee      eeee X       zz           ee          eK      De eeee eeezuK5###EEGe\n"
	"eeeeeeeGeeeee5X9ee KWeeeeeee#eeeeeeX e        ee         ee  ee  9eeeeeeeeeE   XeeeeeK eeeeee##DDXX9\n"
	"eeeeeeeeX ee,W#  e     Eeeeeeeee   ,Xe        ee,e      ee       eeee eeeeeeeeG  # eeeKeeeeeeeeeeEeE\n"
	"eeeeeeeee     eeD      5 eeeeeEeeGeee,         eeK     ee D    eee   eeeezEeeeyeX u ye Eeeeeeeeeeee9\n"
	"eeeeeeeeeeee e W5eeeG        eeeee          ,    eeeeeee   u eee  eGeeE#EeeEeeeee DuEe e eDueeGeeeee\n"
	"eeeeeeeeeeeeee X  z Ke eu  e  eeee           e, ee ,e      eeX    eeeEEEee  Xeeeeeeeee e eeeW9eyeeee\n"
	"eeeeeeeeeeeeeeeeeeeeeeXeee eeK     uX eeeeDz    ee     e  ee ye ueeGGeeeeee eeeeee eee e eee Ke,Geee\n"
	"eeeeeeeeeeeeeeeeEGW  EGeee e e e#     ey   e eeeeeee#eeeeee    eee9eeeeeeEeeeeeDG  Kee e  eee5E e5ee\n"
	"eeeeeeeeeeeeeeeeeeeeEe9  GGeee           ey         eee    e, eeeeeeeeeee   ee,eyee Ee    e9eeG   ue\n"
	"eeeeeeeeeeeeeeeeeeeeeeeeze#   ee        ezeeeeeee     ee   eeeeeeeeeee     eeeeeeee eee  e5eezeeX   \n"
	"eeeeeeeeeeeeeeeeeeeeeeeeGeeeee eee# ee9eGeeee5   yu     eDeeeeeeeeeeee   eeee#eeGe eDeee W eee,eee  \n"
	"eeeeeeeeeeeeeeeeeeeeeeeeGeeeeeeeeeeeeeeWeee  EeezeeeeeeeeeeeeeeeeeGE  eeeeXeeXeE ee ueeX G D#eeGeuee\n"
	"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeG9GeE9EzE,5e9eeee eX  Eee ee Wyeu  e   Eeeee   eeeee zeeee    eGee,e9Ge\n"
	"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeGeE#E##9EzE E#KyeeE  GeX D  ee eE  eeeeeee   eeeeW    e ee e   Ezeeee5 \n"
	"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeEEEeG99E9D  eeX9eeee Xe Ee e# e# e# e9 e  eee   ,e   e ee     eeXEeeX \n"
	"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeEGEEE9#yueeeee  eeeeWe9ee eG  5     e#eeeKe     #K e# eee    eee eeee\n"
	"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeG9EG#y5eeeeeeeeX XzXXeeEeK#u e u    ee   e e    XE9e eee    yee   ee\n"
	"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeGEEE#KEeeeeeeeeeeeDu ,Keee9eeEe  eee     ,E    eDeeWee ee    Deeee  u\n"
	"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeGE#yeeeeeeeeeeeeeee9eee            Xe e     WE   E  ez e    ueeeee9y\n"
	"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeGE#XeeeeeeeeeeeeeeeeEe eee eeG E eeE G Deuueeeeye Ke #ee        ee #e\n"
	"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeGEE99eeeeeeeeeGEGeeeeeeeu  eeeeeze#95e Ku G#Deee5      ,e ueue  K ue  e\n"

};

const char display[] =
"+--------------------------------------------------------------------------------------------------+\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"+--------------------------------------------------------------------------------------------------+\n"
"|                                                                                                  |\n"
"+--------------------------------------------------------------------------------------------------+\n"
"|                                                                                                  |\n"
"+--------------------------------------------------------------------------------------------------+\n";

const char* const characterPicture[] =
{
	"+--------------------------------------------------------------------------------------------------+\n"
	"|                                               ````..``                                           |\n"
	"|                                             ``........`                                          |\n"
	"|                                            ``.--.----..`                                         |\n"
	"|                                           ``...-:///--``                                         |\n"
	"|                                          .+hhysshsoydhh/.                                        |\n"
	"|                                          omMdooohhysymNdo`                                       |\n"
	"|                                          .hNdsoysosodNmmy.                                       |\n"
	"|                                         ``-mNyossosmMmdh:                                        |\n"
	"|                                      ``-.../MNhoshNNms:`                                         |\n"
	"|                                   ````.-oso++hmNmdyo/-``                                         |\n"
	"|                                ````....-:oyhhyhdhso/:..````                                      |\n"
	"|                             ``-:::--...--/+syyhdss/:--.......`                                   |\n"
	"|                            `.-/::/:-----:/+syyhhsys+/:-.....-.`                                  |\n"
	"|                           `.-+/o+o/::::://+oysyyyyso+/:-....+:.                                  |\n"
	"|                          ``://s+o+:://++++oossyyyysso+/:-.-:s/-`                                 |\n"
	"|                          `.-ssshho--:/ooooossssyssssso+::--/o+.`                                 |\n"
	"|                         ``+:oyyhdyo:--+oooosssssssssss+-:+-os/.`    `.`                          |\n"
	"|                        ``./sohhhmhso--//sososssssssssso./sohyo:``:ohmNy                          |\n"
	"|                       `--/+yyysyhooo-.:/soosssosssssoos-/sdho:/o+hNmy/.                          |\n"
	"|                       `-osyddo:yyd/o/.-//++/o//+++/+/+/:/syo+/+ohy+`                             |\n"
	"|                       ..:+ooy:`yyooo/::oooo+s+oo+++o+ooshmdhoosooo-                              |\n"
	"|                       `.-:////.yhhyo+/+sysssssooooosyhdNdyyo+++++:`                              |\n"
	"|                        ``:::--:/yyys++ysysooooooydNNNmhys`+ooo++o:                               |\n"
	"|                         ``.-/.-//+syosyyyso++///hmhsssysy: ----.                                 |\n"
	"|                           ``./+:::/oosooo+//:::/oooosyssso                                       |\n"
	"|                              .-.:++/////+::/+ooooooosssss+.                                      |\n"
	"|                                `-//+/://+oooooooooooosyso+-                                      |\n"
	"|                                `./:://:+yy++ooosoooo++os/+-                                      |\n"
	"|                                ``.:/+++/+syo++ooooooo+ooo/`                                      |\n"
	"|                                `.-/+ossoo+oso+ooooooosoo+:                                       |\n"
	"|                                yyshsyyysssssssssssyyyssyyy.                                      |\n"
	"|                               :hdmNNMMMMMNNNNNNNNNNMMMNNNms                                      |\n"
	"|                               yddNNNNMMMMMMMMMMNMMMMMMNNNNm`                                     |\n"
	"|                              .hdmmNNNNNMMMMMMNMNMMMMNNNNNNN:                                     |\n"
	"+--------------------------------------------------------------------------------------------------+\n"
	,
	"+--------------------------------------------------------------------------------------------------+\n"
	"|                                       eeGzz#ze#eeeeE     ,                                       |\n"
	"|                             eeeee    WeeeeGzDe,e9uKeee   u                                       |\n"
	"|                           ee    ee eee eeKeeDeKe e G9ee                                          |\n"
	"|                           e  yWK ee   eu   eeeueX5 e9XeW                                         |\n"
	"|                          De XyK  Xeee       ee e uee#5eX                                         |\n"
	"|                         eee9     K    eeeeee e eee9DzXe  ,                                       |\n"
	"|                         e##eeeu    Weee    XeeXeXX#9zEe                                          |\n"
	"|                         eee#eeee       zee   ee9EEE#Ee#  ,                                       |\n"
	"|                         e eeeeGeeee  u    ,  eeeGeeeee                                           |\n"
	"|                         e  GXeeeeeeeee       eEGGeeeezeee5                                       |\n"
	"|                          e    eeeeeee  eee   e5#9#Ee , E e                                       |\n"
	"|                         eeG           ee9zeeeXW#9eeeeeee ee                                      |\n"
	"|                       #eeeeeD        zeeeeeeeeGK  ee  eee  e                                     |\n"
	"|                   5eeeeeGDu#eeeeeeeeeeE5WKuuuX#eeeeeeeeeeeeeK                                    |\n"
	"|                 Ee  yee9yKWzGeeeee#5yy5XDDzzzXXDD9e  X      ee                                   |\n"
	"|                e   ee#DEeeee#,eG uX#EeeE9##9EE999ee  e    Wu ee                                  |\n"
	"|            ,   e5eee##ee#   eXeX#eeeeeeeeeeeeeeeee  ee  e   9 ue                                 |\n"
	"|               eeEEzz#ee    eeWeeee#eeeeX        eGyeeWEDy u ueee                                 |\n"
	"|              eez##9#ze   Kee#yeD ,ee             GG eeuXeeX#W  e                                 |\n"
	"|              eD#####zeeeeeGD#zEeEXe                  eeeee   Xee      eeeeeeee                   |\n"
	"|              eX######DzDDD###DzzDWe                     GeeeeeKEe EeeeX      Dee                 |\n"
	"|              eD###9#######z#zzzz9#ee                         eG,9e     K5zDy    e                |\n"
	"|              eez############9EEEEEGee                      Xeeeu ue KX#DK        e               |\n"
	"|          ,    e9D9##z#999#9E9EGGE9GKe                   yeee Kee#ee95      yzzXW  e              |\n"
	"|               ee9zEEEE9EE99EEEEeee9 e                 eee    yeee      ,5XyWKu    #e             |\n"
	"|                eeE#EEE99EEGGGGGeeeu ee             KeeD   uWu       W5XyuK,    KWK e9            |\n"
	"|                 eeE9EE9#EeeeGEGE9955ee           Kee   ,KWWW     5DyWuuu,  uyXDzz9Eee            |\n"
	"|                  ee99Eee9KXeeeeGeeeGGe9          e9ee   K,   ,y5Wu ,uu,uKWDz#DzEeee9e            |\n"
	"|                   ee999GeeeeeeeGeeeE#ee          e  Xez  u,WyWu,uWWWKyX#9E9#Eeeeeeeue            |\n"
	"|                   WezE9E9ze eeeGeeeee9ee         e,uKKee  uKuuWKKuKD9EEEEeeeeeeeGu ee            |\n"
	"|                    ez9##9Ee  EeeEeeGeGEeD        5e,XXXee  WKuuu5zGE99eeeeeee#K  ee,             |\n"
	"|                    ee#E99eee   eeEE9GeEee         ee5XyXee   y#eeeeeeeeeee#W  5ee                |\n"
	"|                    eeD##9ee e   ee9EEeEGee         eeXXD9eeKEeeeeeeeee95,  ueee                  |\n"
	"|                    5eD##EeK e   Wee9GeeeGze         eezDzzeeeeeeeeEXW   9eee                     |\n"
	"+--------------------------------------------------------------------------------------------------+\n"
	,

	"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*****.........**************@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@********...........**************@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@**@@@*********..............******.....***@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@@@@@@@***@@@@********............... ..*****.....**@@@@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@@@**@**.*@@@******..*******...... .......**@********@@@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@@***@*..@@@*****@@@@**@******.......******..*@@@@@@***@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@**@@@*.*@@@*******************........***@@**@@@@@@@@*@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@**@@@@.*@@*****..........*****...............@@@@**@@@*@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@*@@*@@*@@@@*****........******...............@**@****@@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@**@@**@@@@@@******........***@**.............****@*****@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@**@***@@@@@********........................*@*******.*@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@**@***@@@@@********...********.****.......*@@.*******.*@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@**@*.***@@@@@*********..*................*@**.***.****.*@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@@**@*.**@@@@@@@*********..............*@@**..************@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@@**@*.***@@@@@@@@@********.........*@@@**...*@*******@*@**@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@@***@***.**@@@@@@@*******........**@@***.*.*@*@****@*@@@**@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@*****@******@@*******...........**@******.***@@***@@@@@@**@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@**************@******............*@***.****@@@@@@*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@@****.@******@@*....*...........*@**.*@**@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@@@*****@@*****@*.....***........*@@**@**@@@@@@@@@@@@@@@@@@@@@@@@@@***@@@@@@@@@\n"
	"@@@@@@@@@@@@@@@@@@@@@@@@@*****@@@***@*....****...........**@@*@@@@@@@@@@@@@@@@@@@@@@@@@@@@****@@@@@@\n"
	"@@@@@@@@@@@*@@@@@@@@@**@****@**@*.****..*****..............*****@@@@@@@@@@@@@@@@@@@@@@@@@@@@***@@@@@\n"
	"@@@@@@@@@**@@@@@@@@***********@**********................     .....*******@*@@@@*@@@@@@@@@@@@*...@@@\n"
	"@@@@@@@@**@@@@@@***..*****************...........                .......********@@@@@@@@*@@****...*@\n"
	"@@@@@@@**@@@@@*..******.........                                    ...............**@@@**@*****@**@\n"
	"@@@@@@@*@@@@****.................                                      ....... .   ..**************.\n"
	"@@@@@@@@@@@@**...................                                        ......    ......*.*********\n"
	"@@@@@@*@@@@***.................                                                     .....*..******.*\n"
	"@@@@@**@@@@***...............                                                       ......*...*.****\n"
	"@@@@@*@@@@@@*................                                                  .   ....  .....**.**.\n"
	"@@@@@@@@@@*...................... ...... ......                                  *     ....****@**@*\n"
	"@@@@@@@@@....................................                                    .*....*.....******.\n"
	"@@@@@@@@.....................................                                     @.................\n"
	"@@@@@@@......................................                                     **................\n"
	"@@@@@@*.......................................                                   .@@*...............\n"
	"@@@@@@*........................................                                  *@@@**.............\n"
	"@@@@@@@..........................................                               .@@@@@****..........\n"
	"@@@@@@@@*..........................................                             .@@@@@@****.........\n"
	"@@@@@@@@@@**..........................................                         *@@@@@@@@****........\n"
                                                                                                 
                                                                                   
};

const char zombiePicture[] =
	"*****++++===:::::..............  ..         ..  ............::::::=======+++++*******#####MMMMMMMMMMMn"
	"##******+++===:::::.........  ..          :==+*.  .  .........:::::======++++++*****######MMMMMMM@@@\n"
	"####****+++===:::::......   ..           .++=*M#.    .........::::=====+++++*****#####MMMMMMM@@@@@@@\n"
	"++++++======::::........ .*##:            +:*++*       ........:::::======+++****####MMMMMMMM#######\n"
	":::::::........          +@@#::    ......=+#**#+..     .........::::.:====+++++*****+=::...    ....:\n"
	"==:::::::...:::......... .@##*====*==:::+*+*M@M*#==:.   .............::::::::===++++++=::.::::=+++==\n"
	"+++======:::::::......... +MMMMMM#**+==:#==+#+==M+##++=    .. . .......:::===++===::=====+***##***##\n"
	"++++======::::::::........  ::::..   .=+M::**+.*#=*M###*.    ......::::=====++*********####****##MMM\n"
	"::::::.....................          .=##*#MMM#MM#@M+*####=. ...::::==+++++**************+++++++++++\n"
	"*****++++++++++=====::::::........... :**M###MMM@@#=  :#MMMM#.:::::::::======++++***######MMMMMMMMMM\n"
	"###*#####*****+++====:::::::::........:+#M##MM#M@#= ....*M@@@+:::=========+++++****#####MMMMMMMM@@@@\n"
	"MMMMMM#######***++++======::::::::::..=+#M+#*@MMM#:..::::::+#+======+++++*******#####MMMMMMM@@@@@@@@\n"
	"MMMMMMMMM##****+++++=========:::::::: +####MMMMMM#.::::========+++++++*****#######M#MMMMM@@@@@@@@@@@\n"
	"#MMM##MM#####****++++++++++=======:. =##MM*#MM#@M*:.:======++++***********####MMMMMMM#MMMMMMMMMMMMM@\n"
	"MMMMMM##M####******++==========:....:#M####M#@M#M#=..:::===+++*****#******##*######MMMM#MMMMMMM@@@@@\n"
	"@@@@MMMMMM######***++**+++==::......##@MMMMMM@M#MM*......::==++***+**######MMMMMMMMMMMMM@MMMMMMMM@MM\n"
	"@@@MMMMMMMM####******++=::.........*M#MMMM@@MMMMMM# ........::==++***######MMMMM@@M@@M@@M@@@MMMM@@M@\n"
	"MMMMMMMMMM#####*#*+==::::::::::.:..#MM#MM@*.@MM#MMM....:::::::::==++++**#######**##MMM@@@@@@@@@@@@@@\n"
	"MMMMMMMM#M####*+==::::::::::::::::.=@MMM@=..*@MMM@#.:::::::::=======++*+**####MMM##*##*#MMMM@@@@@@@@\n"
	"MMMMMMMMM#*+===========:::::::::::=@@@@@*.:::@@@@@::::::::::=======+++++++**#######M##MMMMMM@@@@@@@@\n"
	"MMM@M#**+++++++++===========::::::*@@@@M.::::M@@@@=:============+++++**********##############MMMM#MM\n"
	"M#**+*+*+++++++++++++==============@@@@=====:*@@@@@=========+++++++**********######MMMMMMMMMMMMMMMM@\n"
	"***************++++++++++==========@MM*=======@@@@@*=+++++++++++*******################MMMMMMMMMMMMM\n"
	"#######**********+++*++++++++++++++@@*=+++==+=#@@@@++++++++**********#############MMMMMMMMMMMMMMMMMM\n"
	"############*********+++*++*++++++#@@*++++++++*@@@@+++************############MMMMMMMMMMMMMMMMMMMM@@\n"
	"###############***************++++@@@@#++++++++*@@M+**********##############MMMMMMMMMMMMMMMMMMMMMMMM\n"
	"MMMMMMMM###########*#***********#@@@@M******+***@@M*****###############MMMMMMMMMMMMMMMMMMMMMM@M@@@@@\n"
	"MMMMMMMMM#################*****M@@@@M#*********#@@@*################M#MMMMMMMMMMMMMMMMM@@@@@@@@@@@@@\n"
	"MMMMMMMMMMMMMM#################@@@@M#**#*#*####M@@@#############MMMMMMMMMMMMMMMMMMMMM@@@@@@@@@@@@@@@\n"
	"MMMMMMMMMMMMMMMMMMMMMMMMMM####M@@@@############M@@@@######M##MMMMMMMMMMMMMMMMMMMMM@@@@@@@@@@@@@@@@@@\n"
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMM#M@@@@MM###########@@@@@M#MMMMMMMMMMMMMMMMMMMMMMMMMMM@@@@@@@@@@@@@@@@@@@\n"
	"@@M@MMMMMMMMMMMMMMMMMMMMMMMMM@@@@@@MM###MMMMM#M@@@@@@MMMMMMMMMMMMMMMMMMMMMMMMM@M@@@@@@@@@@@@@@@@@@@@\n"
	"@@MMMMMM@MMMMMMMMMMMMMMMMMMM@@@@@@@MMMMMMMMMMM@@@@@@@@MMMMMMMMMMMMMMMMMMMMMM@@@@@@@@@@@@@@@@@@@@@@@@\n"
	"@MMMMM@M@@MMMMMMMMMMMMMMMMM@@@@@@@@@MMMMMMMMMM@@@@@@@@@MMMMMMMMMMMMM@MMMM@@M@@@@@@@@@@@@@@@@@@@@@@@@\n";

