const char* const opening[] = {
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
	"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111\n"
};

const char display[] =
"+--------------------------------------------------------------------------------------------------+\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"|                                                                                                  |\n"
"+--------------------------------------------------------------------------------------------------+\n"
"|                                                                                                  |\n"
"+--------------------------------------------------------------------------------------------------+\n"
"|                                                                                                  |\n"
"+--------------------------------------------------------------------------------------------------+\n";

const char* const characterPicture[] =
{
	"+--------------------------------------------------------------------------------------------------+\n"
	"|                                               ````..``                                           |\n"
	"|                                             ``........`                                          |\n"
	"|                                            ``.--.----..`                                         |\n"
	"|                                           ``...-:///--``                                         |\n"
	"|                                          .+hhysshsoydhh/.                                        |\n"
	"|                                          omMdooohhysymNdo`                                       |\n"
	"|                                          .hNdsoysosodNmmy.                                       |\n"
	"|                                         ``-mNyossosmMmdh:                                        |\n"
	"|                                      ``-.../mNhoshNNms:`                                         |\n"
	"|                                   ````.-oso++hmNmdyo/-``                                         |\n"
	"|                                ````....-:oyhhyhdhso/:..````                                      |\n"
	"|                             ``-:::--...--/+syyhdss/:--.......`                                   |\n"
	"|                            `.-/::/:-----:/+syyhhsys+/:-.....-.`                                  |\n"
	"|                           `.-+/o+o/::::://+oysyyyyso+/:-....+:.                                  |\n"
	"|                          ``://s+o+:://++++oossyyyysso+/:-.-:s/-`                                 |\n"
	"|                          `.-ssshho--:/ooooossssyssssso+::--/o+.`                                 |\n"
	"|                         ``+:oyyhdyo:--+oooosssssssssss+-:+-os/.`    `.`                          |\n"
	"|                        ``./sohhhmhso--//sososssssssssso./sohyo:``:ohmNy                          |\n"
	"|                       `--/+yyysyhooo-.:/soosssosssssoos-/sdho:/o+hNmy/.                          |\n"
	"|                       `-osyddo:yyd/o/.-//++/o//+++/+/+/:/syo+/+ohy+`                             |\n"
	"|                       ..:+ooy:`yyooo/::oooo+s+oo+++o+ooshmdhoosooo-                              |\n"
	"|                       `.-:////.yhhyo+/+sysssssooooosyhdNdyyo+++++:`                              |\n"
	"|                        ``:::--:/yyys++ysysooooooydNNNmhys`+ooo++o:                               |\n"
	"|                         ``.-/.-//+syosyyyso++///hmhsssysy: ----.                                 |\n"
	"|                           ``./+:::/oosooo+//:::/oooosyssso                                       |\n"
	"|                              .-.:++/////+::/+ooooooosssss+.                                      |\n"
	"|                                `-//+/://+oooooooooooosyso+-                                      |\n"
	"|                                `./:://:+yy++ooosoooo++os/+-                                      |\n"
	"|                                ``.:/+++/+syo++ooooooo+ooo/`                                      |\n"
	"|                                `.-/+ossoo+oso+ooooooosoo+:                                       |\n"
	"|                                yyshsyyysssssssssssyyyssyyy.                                      |\n"
	"|                               :hdmNNMMMMMNNNNNNNNNNMMMNNNms                                      |\n"
	"|                               yddNNNNMMMMMMMMMMNMMMMMMNNNNm`                                     |\n"
	"|                              .hdmmNNNNNMMMMMMNMNMMMMNNNNNNN:                                     |\n"
	"+--------------------------------------------------------------------------------------------------+\n"
	,
	"+--------------------------------------------------------------------------------------------------+\n"
	"|                                       eeGzz#ze#eeeeE     ,                                       |\n"
	"|                             eeeee    WeeeeGzDe,e9uKeee   u                                       |\n"
	"|                           ee    ee eee eeKeeDeKe e G9ee                                          |\n"
	"|                           e  yWK ee   eu   eeeueX5 e9XeW                                         |\n"
	"|                          De XyK  Xeee       ee e uee#5eX                                         |\n"
	"|                         eee9     K    eeeeee e eee9DzXe  ,                                       |\n"
	"|                         e##eeeu    Weee    XeeXeXX#9zEe                                          |\n"
	"|                         eee#eeee       zee   ee9EEE#Ee#  ,                                       |\n"
	"|                         e eeeeGeeee  u    ,  eeeGeeeee                                           |\n"
	"|                         e  GXeeeeeeeee       eEGGeeeezeee5                                       |\n"
	"|                          e    eeeeeee  eee   e5#9#Ee , E e                                       |\n"
	"|                         eeG           ee9zeeeXW#9eeeeeee ee                                      |\n"
	"|                       #eeeeeD        zeeeeeeeeGK  ee  eee  e                                     |\n"
	"|                   5eeeeeGDu#eeeeeeeeeeE5WKuuuX#eeeeeeeeeeeeeK                                    |\n"
	"|                 Ee  yee9yKWzGeeeee#5yy5XDDzzzXXDD9e  X      ee                                   |\n"
	"|                e   ee#DEeeee#,eG uX#EeeE9##9EE999ee  e    Wu ee                                  |\n"
	"|            ,   e5eee##ee#   eXeX#eeeeeeeeeeeeeeeee  ee  e   9 ue                                 |\n"
	"|               eeEEzz#ee    eeWeeee#eeeeX        eGyeeWEDy u ueee                                 |\n"
	"|              eez##9#ze   Kee#yeD ,ee             GG eeuXeeX#W  e                                 |\n"
	"|              eD#####zeeeeeGD#zEeEXe                  eeeee   Xee      eeeeeeee                   |\n"
	"|              eX######DzDDD###DzzDWe                     GeeeeeKEe EeeeX      Dee                 |\n"
	"|              eD###9#######z#zzzz9#ee                         eG,9e     K5zDy    e                |\n"
	"|              eez############9EEEEEGee                      Xeeeu ue KX#DK        e               |\n"
	"|          ,    e9D9##z#999#9E9EGGE9GKe                   yeee Kee#ee95      yzzXW  e              |\n"
	"|               ee9zEEEE9EE99EEEEeee9 e                 eee    yeee      ,5XyWKu    #e             |\n"
	"|                eeE#EEE99EEGGGGGeeeu ee             KeeD   uWu       W5XyuK,    KWK e9            |\n"
	"|                 eeE9EE9#EeeeGEGE9955ee           Kee   ,KWWW     5DyWuuu,  uyXDzz9Eee            |\n"
	"|                  ee99Eee9KXeeeeGeeeGGe9          e9ee   K,   ,y5Wu ,uu,uKWDz#DzEeee9e            |\n"
	"|                   ee999GeeeeeeeGeeeE#ee          e  Xez  u,WyWu,uWWWKyX#9E9#Eeeeeeeue            |\n"
	"|                   WezE9E9ze eeeGeeeee9ee         e,uKKee  uKuuWKKuKD9EEEEeeeeeeeGu ee            |\n"
	"|                    ez9##9Ee  EeeEeeGeGEeD        5e,XXXee  WKuuu5zGE99eeeeeee#K  ee,             |\n"
	"|                    ee#E99eee   eeEE9GeEee         ee5XyXee   y#eeeeeeeeeee#W  5ee                |\n"
	"|                    eeD##9ee e   ee9EEeEGee         eeXXD9eeKEeeeeeeeee95,  ueee                  |\n"
	"|                    5eD##EeK e   Wee9GeeeGze         eezDzzeeeeeeeeEXW   9eee                     |\n"
	"+--------------------------------------------------------------------------------------------------+\n"
	,
	                                                                                                    
	"+--------------------------------------------------------------------------------------------------+\n"
	"|                                                                                                  |\n"
	"|                                                                                                  |\n"                                                                                               
	"|                              zeeeeeeeeeeeeeeee                                                   |\n"
	"|                          eeeeeeeeeeu      EeeeeeeeD       ueeeeeeeeeeeeeeeeeW                    |\n"
	"|                         eee                      eeeeKeeeeeeeeeeGEWKXEeeeeeeeeeeee9              |\n"
	"|                        eee                          eeez                        eeeeee           |\n"
	"|                       eee                          Dee                             eeeD          |\n"
	"|                      eee                          eee                             Keee           |\n"
	"|                     ee5                          eee                             eeee5           |\n"
	"|                    eey                          eee                             eeDee            |\n"
	"|                   ee5                          yee                             eeG ee            |\n"
	"|                  ee                           yee                             eee eee            |\n"
	"|                 ee                           zee                             eee  ee             |\n"
	"|                ee                            ee                             9ee  eee             |\n"
	"|               ee                            ee                             zee  eee              |\n"
	"|             eee                            ee                             Xee  eee               |\n"
	"|            eee                            ee                             Kee  eee                |\n"
	"|           eee                           #ee                              ee  eee                 |\n"
	"|          eee                           Xee                              ee  eee                  |\n"
	"|         eee                           eee                              ee, eee                   |\n"
	"|        eee                            ee                      E      eeeu uee                    |\n"
	"|       eeD                            ee                      eeeeeeeeeee Dee                     |\n"
	"|      yeeGeeeeeeeeeeeeeeeeeeeee      ee     yGeeeeeeeeE5      e   Ge uee  ee                      |\n"
	"|     eeeeeeW               ueeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee,  eee  ee                       |\n"
	"|     9ee                          Eeee                        5eeeeeeW  ee                        |\n"
	"|       ee                      ee5 ee  yeeeE                      ee   ee                         |\n"
	"|        ee                   K5eeu ee      uX9                    ee  ee                          |\n"
	"|        Geeeeeeeeeeeeeeeeeeeee     eee5ee#,                      uee ee                           |\n"
	"|         eee9              yeeeeeeDWeD     XeeeeeeeeeeeeeeXu     ee ee                            |\n"
	"|                                 Eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee                             |\n"
	"|                                                                eeee                              |\n"
	"|                                                                                                  |\n"
	"|                                                                                                  |\n"
	"|                                                                                                  |\n"
	"+--------------------------------------------------------------------------------------------------+\n"                                                                                                   
                                                                                   
};	                          

